# base - .github/workflows/publish.yml - beg
# Publishing packages to npm and GitHub Packages
# https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-npm-and-github-packages
name: publish
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:


  job1:
    strategy:
      matrix:
        architecture:
          # - arm64
          - x64
          # - x86
        node_version:
          # - 18
          - 20
          # - 22
        os:
          # - macos-latest
          - ubuntu-latest
          # - windows-latest
    name: >
      job1
      node
      v${{ matrix.node_version }}
      ${{ matrix.architecture }}
      ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    steps:

      # Setup .npmrc file to publish to GitHub Packages
      - run: rm -f /home/runner/work/_temp/.npmrc
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          # scope: '@octocat'
      # Publish to GitHub Packages
      - run: sh jslint_ci.sh shCiPublishNpm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          NPM_REGISTRY: github

      # Setup .npmrc file to publish to npm
      - run: rm -f /home/runner/work/_temp/.npmrc
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          registry-url: 'https://registry.npmjs.org'
      # Publish to npm
      - run: sh jslint_ci.sh shCiPublishNpm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_REGISTRY: npm
# base - .github/workflows/publish.yml - end


  publish_pypi:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/sqlmath/
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      # retrieve your distributions here
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: sh jslint_ci.sh shCiPublishPypi
      # publish to pypi
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
